### PR TITLE
add AngularConnect 2019 info

### PR DESCRIPTION
**Pull request by petebacondarwin**

### CODE REVIEW

**Comment by petebacondarwin** [comment]
❤️

**Comment by anacidre** [comment]
Good luck with everything!!! <3

**Comment by petebacondarwin** [comment]
Thanks! What did I do wrong with the link?

Screenshot 2019-06-03 at 11 26 12

**Comment by petebacondarwin** [comment]
Oh I see. You use the link address as the text of the link.. I'll change that...

**Comment by anacidre** [comment]
I already updated it for you :)

**Pull request merged**
