### PR TITLE
Add AngularAthens meetup

### PR DESCRIPTION
**Pull request by bampakoa**
Add Angular Athens meetup for April 2019

### CODE REVIEW

**Comment by stevermeister** [comment]
👍

**Comment by anacidre** [comment]
Hey! I see that in the title this is meant to be a meetup but on line 151 we have "type": "conference".. Once this is cleared up I'll merge! Thanks a lot!!

**Comment by bampakoa** [comment]
thanks for pointing out @anacidre . This is now ready 😃

**Comment by anacidre** [comment]
Awesome! Thanks for adding!!

**Pull request merged**
